---
# This will be the subscriber for the Trigger
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: crawler
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "0"
    spec:
      containers:
        - image: quay.io/maxgio92/cloudevents-crawler
---
# Knative Eventing Trigger to trigger the crawler service
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: crawler
  namespace: default
spec:
  broker: default
  filter:
    attributes:
      type: dev.knative.crawling.pending
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: crawler
---
# Knative Eventing Trigger to trigger the crawler service
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: crawler-vpn
  namespace: default
spec:
  broker: default
  filter:
    attributes:
      type: dev.knative.vpn.ready
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: crawler
