---
# This will be the subscriber for the Trigger
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: vpn-provisioner
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "0"
    spec:
      containers:
        - image: quay.io/maxgio92/cloudevents-vpn-provisioner
---
# Knative Eventing Trigger to trigger the vpn-provisioner service
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: vpn-provisioner
  namespace: default
spec:
  broker: default
  filter:
    attributes:
      type: dev.knative.vpn.pending
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: vpn-provisioner
